### ISSUE TITLE
Download bytes are not increasing but still progress_callback is getting triggered

### ISSUE THREAD

**Issue by Un-0wn** [TechShreyash/techzdl#1]
Download bytes are not increasing but still progress_callback is getting triggered.

**What happens is that I have set progress text on this callback. When progress_callback is triggered this text will edit according to the downloaded bytes**. But I am getting this error, **_Telegram says: [400 MESSAGE_NOT_MODIFIED]_**

Because in progress message downloaded bytes remains same but still when progress_callback is called then this error comes.

**Comment by TechShreyash** [comment]
You can modify your callback function to check whether the progress (size downloaded) has updated or not

And then update the message

**Comment by Un-0wn** [comment]
yes i did that but i think you should do that too, because download bytes will not increase and progress callback will keep on triggering, this will display the same text again and again, or else put something like update only when bytes change

**Comment by TechShreyash** [comment]
@Un-0wn Yeah, ig that would be better

**Comment by TechShreyash** [comment]
Made changes as recommended by you in the latest techzdl v1.2.2 version

you may update the package and use
