### ISSUE TITLE
Response payload is not completed

### ISSUE THREAD

**Issue by Un-0wn** [TechShreyash/techzdl#3]
Why i m getting this error & how to solve it

TechZDL - TSLDUQ - ERROR - Error downloading chunk 398458880-403701759: Response payload is not completed: <ContentLengthError: 400, message='Not enough data for satisfy content length header.'>

Stack trace - "https://ctxt.io/2/AAAYIvIJFg"

**Comment by TechShreyash** [comment]
@Un-0wn Can you provide the file url for me to test

**Comment by Un-0wn** [comment]
"https://d.nephobox.com/file/8f16998b461939626cfc242ba0b82cf0?fid=4399013972090-250528-886098680875893&dstime=1719567839&rt=sh&sign=FDtAER-DCb740ccc5511e5e8fedcff06b081203-%2B9%2FHJyXbmx2pTJ9oITL016zAFWo%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8780338088022797894&dp-callid=0&r=206337607&sh=1&region=jp"

**Comment by Un-0wn** [comment]
"https://d.terabox.app/file/8f16998b461939626cfc242ba0b82cf0?fid=4399013972090-250528-886098680875893&dstime=1719568013&rt=sh&sign=FDtAER-DCb740ccc5511e5e8fedcff06b081203-UBQWkG6xtfdr0FZTfkp34ZGWZhE%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8780384961685417933&dp-callid=0&r=558226178&sh=1%C2%AEion=jp"

**Comment by Un-0wn** [comment]
> @Un-0wn Can you provide the file url for me to test

"https://d.terabox.app/file/8f16998b461939626cfc242ba0b82cf0?fid=4399013972090-250528-886098680875893&dstime=1719568013&rt=sh&sign=FDtAER-DCb740ccc5511e5e8fedcff06b081203-UBQWkG6xtfdr0FZTfkp34ZGWZhE%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=8780384961685417933&dp-callid=0&r=558226178&sh=1%C2%AEion=jp"

**Comment by TechShreyash** [comment]
@Un-0wn Some problem in the download server

The download link very slow, i am getting 20 kbps speed

You can try downloading with single threaded mode

**Comment by Un-0wn** [comment]
If download speed is slow then this error will come right 😒

**Comment by TechShreyash** [comment]
@Un-0wn Download speed too slow directly means that  there's high chance of disconnection
