### ISSUE TITLE
Brother, this is your package problem, you get this error - "VNZXRQ:Error downloading chunk 78643200-83856361: Response payload is not completed: <ContentLengthError: 400, message='Not enough data to satisfy content length header.'>" It is working fine in my area

### ISSUE THREAD

**Issue by Un-0wn** [TechShreyash/techzdl#4]
Brother, this is your package problem, im getting this error - "VNZXRQ:Error downloading chunk 78643200-83856361: Response payload is not completed: <ContentLengthError: 400, message='Not enough data to satisfy content length header.'>"
I checked 4, 5 direct links
It is working fine in aria2p,
even download link speed is fast

**Comment by TechShreyash** [comment]
try with single threaded mode 

and please provide the links you are facing problem with, cuz its not a general issue with every link. it is specific to the site where you are trying to download the file from
